### ISSUE TITLE
Container compute resources cannot be unmarshalled

### ISSUE THREAD

**Issue by ae6rt** [ericchiang/k8s#48] opened 2017-05-06 13:39 UTC
Thank you for this package.

In an attempt to unmarshal a Deployment, I find compute resources such as cpu and memory limits do not unmarshal.

## Backing information

  * package version:  v0.3.0
  * Runtime environment:  centos7 container

## Input

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: the-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: the-app
  template:
    metadata:
      labels:
        name: the-app
      name: the-app
    spec:
      containers:
      - name: the-app
        image: docker-registry.example.com/acme/the-app:develop
        ports:
        - containerPort: 5586
          name: server-port
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
```
## Desired action

Attempt to unmarshal this resource, where *data* is a byte slice backing the input

```
var t v1beta1.Deployment
if err := json.Unmarshal(data, &t); err != nil {
    log.Fatal(err)
}
...
```

## Result

```
2017/05/06 13:31:38 json: cannot unmarshal string into Go struct field ResourceRequirements.limits of type resource.Quantity
```

## Workaround

Remove the compute resources 

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: the-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: the-app
  template:
    metadata:
      labels:
        name: the-app
      name: the-app
    spec:
      containers:
      - name: the-app
        image: docker-registry.example.com/acme/the-app:develop
        ports:
        - containerPort: 5586
          name: server-port
```

This input can be successfully unmarshaled into a Deployment.

**Comment by ericchiang** [comment] 2017-05-06 16:15
Hi @ae6rt,

Unlike client-go, this package doesn't attempt to support the JSON and YAML serialization of Kubernetes resources (with an exception for thirdpartyresources). The resources are only generated for protobuf serialization so we can talk to the API.

This was brought up in a previous issue https://github.com/ericchiang/k8s/issues/8

Since this is sort of "working as intended" I'm going to close this issue out.

If I've misunderstood something or you have some suggestions for how I can document this restriction better please comment.

**Closed by ericchiang** 2017-05-06 16:15 UTC
